### ISSUE TITLE
Does it support Ollama?

### ISSUE THREAD

**Issue by hemangjoshi37a** [gptscript-ai/gptscript#136]
Does it support Ollama?

**Comment by rinor** [comment]
iirc, not directly because of a missing (different) endpoint on Ollama regarding models (related to Ollama openai api compat), but you can use [litellm](https://github.com/BerriAI/litellm) proxy and that should make it possible to use ollama, among other supported models.

so, iirc

- `gptscript` -> `local ollama` = :x: 
- `gptscript` -> `litellm` -> `local ollama` = :ok:

**Comment by prologic** [comment]
What's the missing endpoint in the Ollama OpenAI compact?

**Comment by hemangjoshi37a** [comment]
@rinor  ok thanks for the solution. closing now.

**Comment by rinor** [comment]
> What's the missing endpoint in the Ollama OpenAI compact?

@prologic iirc it was the `/models` endpoint
