### ISSUE TITLE
Running the "Hello World" example returns a 404

### ISSUE THREAD

**Issue by theutz** [gptscript-ai/gptscript#143]
I get a proper response via `curl https://get.gptscript.ai`, but not when I run the example provided:

```
gptscript https://get.gptscript.ai/echo.gpt --input 'Hello, World!'
```

**Comment by rinor** [comment]
That's because there may be  an "issue" handling urls and paths around https://github.com/gptscript-ai/gptscript/blob/5c1817701aaeddb661a176d5b6ee70d2839801f2/pkg/loader/url.go#L66 that causes 
- `https://get.gptscript.ai/echo.gpt` to become 
- `https://get.gptscript.ai//echo.gpt` (double slash on path) hence the 404

```sh
$ gptscript 'https://get.gptscript.ai/echo.gpt' --input 'Hello, World!' 
2024/03/11 11:41:39 error loading https://get.gptscript.ai//echo.gpt: 404 Not Found
```

**Comment by rinor** [comment]
fixed by https://github.com/gptscript-ai/gptscript/pull/165

**Comment by theutz** [comment]
Can confirm that this is fixed! Thank you!
