### ISSUE TITLE
Not able to run credential tool with "--ui" option.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/gptscript#469]
Steps to reproduce the problem:
1. Launch UI using - ` GPTSCRIPT_CHAT_UI_TOOL=github.com/gptscript-ai/ui@v2 gptscript --ui `

2. Execute the following script that uses credentials:

```
Tools:  github.com/gptscript-ai/gpt4-v-vision, github.com/gptscript-ai/dalle-image-generation
chat: true

Describe the image in file file:///Users/sangeethahariharan/Downloads/grocerylist.png
```

3. Following error is seen:

<img width="1233" alt="Screenshot 2024-06-10 at 12 45 43 PM" src="https://github.com/gptscript-ai/gptscript/assets/122560863/81dc7890-9f7c-4e5e-a95f-482049cc1829">

**Expected Behavior:**
Should be prompted to enter the credentials.

**Comment by cjellick** [comment]
Played with this one a bit and can reproduce.

Datapoint: If I run this from the TUI and i enter the credential there, then it works from the UI (because it doesnt have to prompt for creds.

So, it's something to do with credential prompting. I wonder if it is because it is doing permissions and the cred prompting back-to-back.

**Comment by sangee2004** [comment]
Tested with latest gptscript ui.

User is prompted to enter credentials when there is a tool that requires credential is called (and credential is not already present).

Able to enter credentials and proceed with scrip execution.
