### ISSUE TITLE
Confusing naming

### ISSUE THREAD

**Issue by thecaralice** [gptscript-ai/gptscript#76]
The project name, GPTScript, suggests that it's a scripting language that doesn't have anything in common with GPT, which is, however, not true as it actually uses a GPT model. Please change the project name to something like LlamaScript in order to adhere to the existing naming tradition like JavaScript, AssemblyScript and RustScript do.

**Comment by ibuildthecloud** [comment]
The name comes from the basic idea of "scripting ChatGPT" because fundamentally under the hood that is what it is doing.

>  suggests that it's a scripting language that doesn't have anything in common with GPT

I don't understand your point, sorry. The intention of the name is that we are "scripting a GPT model" GPT mean a class of LLM, namely OpenAI GPT-4. Can you please clarify what is incorrect about that or confusing?  For example, what about LlamaScript would make the name more understandable.  Llama as I understand is a specific model architecture used by Meta. We don't do anything specific with Llama and in the current state we do not work with Llama2 models.

**Comment by thecaralice** [comment]
JavaScript does not use Java, AssemblyScript does not use assembly, RustScript does not use Rust. Nevermind, just a stupid midnight joke.

**Comment by ibuildthecloud** [comment]
Well now I feel stupid :)
